name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [24.x] # Ahora usamos Node 24

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      working-directory: /home/ubuntu/APPTECH/DesarrolloFullstack2

    - name: Build
      run: npm run build --if-present
      working-directory: /home/ubuntu/APPTECH/DesarrolloFullstack2

    - name: Run tests
      run: npm test
      working-directory: /home/ubuntu/APPTECH/DesarrolloFullstack2
