name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Build
        run: npm run build --if-present
        working-directory: ${{ github.workspace }}/WebAppTech/appweb
        env:
          CI: false
          
      - name: Build
        run: npm run build --if-present
        working-directory: ${{ github.workspace }}/WebAppTech/appweb

      - name: Run tests
        run: npm test
        working-directory: ${{ github.workspace }}/WebAppTech/appweb
